package edu.wright.crowningkings.desktop;

//import edu.wright.crowningkings.base.UserInterface;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Image;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JTextPane;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JScrollBar;
import java.awt.TextArea;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import java.awt.Color;
import javax.swing.border.EtchedBorder;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.GridLayout;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import java.awt.Panel;
import java.awt.Font;
import javax.swing.ScrollPaneConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class CheckersLobbyUI extends JFrame{

	//private static final long serialVersionUID = 1L;
	
	//Not all of these are used might use them in the futre
	private JPanel checkersMainPanel;
	private JTextField messageTextField;
	private JTextArea currentUsersTextArea;
	private JTextArea lobbyChatTextArea;
	private JPanel gamePanel;
	private JPanel currentLobbyPanel; //Might not need this later on
	private Image im = new ImageIcon("C:\\Users\\Michael\\Pictures\\GameImages\\checkerboard.jpg").getImage();
	private Graphics g;


	/**
	 * Create the frame.
	 * Generated By WindowsBuilder Pro
	 * Variable names changed for Clarity
	 */
	public CheckersLobbyUI() {
		setResizable(false);
		setBackground(new Color(0, 0, 0));
		setTitle("Checkers Game");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1366, 768);
		checkersMainPanel = new JPanel();
		checkersMainPanel.setBackground(new Color(0, 0, 0));
		checkersMainPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(checkersMainPanel);
		checkersMainPanel.setLayout(null);
		
		JLabel title = new JLabel("");
		title.setIcon(new ImageIcon("C:\\Users\\Michael\\Pictures\\GameImages\\temptitle.png"));
		title.setFont(new Font("Castellar", Font.PLAIN, 48));
		title.setHorizontalAlignment(SwingConstants.CENTER);
		title.setForeground(Color.WHITE);
		title.setBounds(0, 0, 1360, 63);
		checkersMainPanel.add(title);
		
		JScrollPane scrollPane_1 = new JScrollPane();
		scrollPane_1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		scrollPane_1.setBounds(167, 62, 1193, 437);
		scrollPane_1.getVerticalScrollBar().setUnitIncrement(15);
		checkersMainPanel.add(scrollPane_1);
		
		currentLobbyPanel = new JPanel();
		scrollPane_1.setViewportView(currentLobbyPanel);
		currentLobbyPanel.setBackground(new Color(46, 139, 87));
		currentLobbyPanel.setName("CurrentLobbyPanel");
		currentLobbyPanel.setPreferredSize(new Dimension(1193, 50000));
		currentLobbyPanel.setBounds(167, 62, 1193, 1000);
		currentLobbyPanel.setLayout(null);
		
//		ImagePanel panel = new ImagePanel(im);
//		panel.setBounds(12, 13, 250, 250);
//		currentLobbyPanel.add(panel);
		
		

		
		JPanel usernamesPanel = new JPanel();
		usernamesPanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		usernamesPanel.setBounds(0, 62, 167, 677);
		usernamesPanel.setName("Usernames Panel");
		checkersMainPanel.add(usernamesPanel);
		usernamesPanel.setLayout(null);
		
		JLabel usersLabel = new JLabel("Users");
		usersLabel.setBounds(59, 11, 46, 14);
		usersLabel.setHorizontalAlignment(SwingConstants.CENTER);
		usernamesPanel.add(usersLabel);
		
		currentUsersTextArea = new JTextArea();
		currentUsersTextArea.setEditable(false);
		currentUsersTextArea.setLineWrap(true);
		currentUsersTextArea.setBounds(0, 0, 4, 22);
		currentUsersTextArea.setName("CurrentUsersTextArea");
		
		JScrollPane usersScrollPane = new JScrollPane(currentUsersTextArea);
		usersScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
		usersScrollPane.setBounds(10, 36, 147, 630);
		usernamesPanel.add(usersScrollPane);
		

		//panel_1.add(textArea_1);
		
		JPanel lobbyChatPanel = new JPanel();
		lobbyChatPanel.setBackground(new Color(255, 255, 255));
		lobbyChatPanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		lobbyChatPanel.setBounds(167, 499, 1193, 210);
		lobbyChatPanel.setName("LobbyChatPanel");
		checkersMainPanel.add(lobbyChatPanel);
		
		lobbyChatTextArea = new JTextArea();
		lobbyChatTextArea.setEditable(false);
		lobbyChatTextArea.setLineWrap(true);
		lobbyChatTextArea.setColumns(107);
		lobbyChatTextArea.setWrapStyleWord(true);
		lobbyChatTextArea.setRows(16);
		lobbyChatTextArea.setName("LobbyChatTextArea");
		
		JScrollPane lobbyChatScrollPane = new JScrollPane(lobbyChatTextArea);
		lobbyChatPanel.add(lobbyChatScrollPane);
		
		
		JPanel messagePanel = new JPanel();
		messagePanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		messagePanel.setBounds(167, 709, 1193, 30);
		messagePanel.setName("MessagePanel");
		checkersMainPanel.add(messagePanel);
		
		messageTextField = new JTextField("username");
		messageTextField.setToolTipText("");
		messageTextField.setHorizontalAlignment(SwingConstants.LEFT);
		messageTextField.setColumns(107);
		messageTextField.setName("MessageTextField");
		messagePanel.add(messageTextField);
		
//		JButton btnNewButton = new JButton("New button");
//		btnNewButton.addActionListener(new ActionListener() {
//			public void actionPerformed(ActionEvent arg0) {
//				if(arg0.get)
//			}
//		});
//		btnNewButton.setBounds(30, 22, 89, 23);
//		checkersMainPanel.add(btnNewButton);
	}
	
//	public JPanel getGamePanel(){
//		GamePanel tempPanel = new GamePanel(im);
//		tempPanel.setBounds(112, 113, 379, 371);
//		//tempPanel.add(gamePanel);
//		tempPanel.setLayout(null);
//		currentLobbyPanel.add(tempPanel);
//		return tempPanel;
//	}
	
	//Get the text filed that a user inputs messages in
	public JTextField getMessageTextField(){
		return messageTextField;
	}
	
	//Get the text of the current users component
	public String getCurrentUsersTextAreaText(){
		return currentUsersTextArea.getText();
	}
	
	//Set the text of the current users component
	public void setCurrentUsersTextAreaText(String username){
		currentUsersTextArea.setText(username + "\n");
	}
	
	//Get all of the text from the lobby chat component
	public String getLobbyChatTextArea(){
		return lobbyChatTextArea.getText();
	}
	
	//Set the text of the lobby chat component
	public void setLobbyChatTextArea(String message){
		lobbyChatTextArea.setText(message);
	}
	public JPanel getLobbyPanel(){
		return currentLobbyPanel;
	}
}
