package edu.wright.crowningkings.desktop;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Image;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JTextPane;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JScrollBar;
import java.awt.TextArea;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import java.awt.Color;
import javax.swing.border.EtchedBorder;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.GridLayout;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import java.awt.Panel;
import java.awt.Font;
import javax.swing.ScrollPaneConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;

public class CheckersLobbyUI extends JFrame{

	//private static final long serialVersionUID = 1L;
	
	//Not all of these are used might use them in the future
	private JPanel checkersMainPanel;
	private JTextField messageTextField;
	private JTextArea currentUsersTextArea;
	private JTextArea lobbyChatTextArea;
	private JPanel lobbyPanel; //Might not need this later on
	private Graphics g;


	/**
	 * Create the frame.
	 * Generated By WindowsBuilder Pro
	 * Variable names changed for Clarity
	 */
	public CheckersLobbyUI() {
		setResizable(false);
		setBackground(new Color(0, 0, 0));
		setTitle("Checkers Game");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1366, 768);
		checkersMainPanel = new JPanel();
		checkersMainPanel.setBackground(new Color(0, 0, 0));
		checkersMainPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(checkersMainPanel);
		checkersMainPanel.setLayout(null);
		
		JLabel title = new JLabel("");
		title.setIcon(new ImageIcon("C:\\Users\\Michael\\Pictures\\GameImages\\temptitle.png"));
		title.setFont(new Font("Castellar", Font.PLAIN, 48));
		title.setHorizontalAlignment(SwingConstants.CENTER);
		title.setForeground(Color.WHITE);
		title.setBounds(0, 0, 1360, 63);
		
		checkersMainPanel.add(title);
		
		JScrollPane scrollPane_1 = new JScrollPane();
		scrollPane_1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		scrollPane_1.setBounds(167, 62, 1193, 437);
		scrollPane_1.getVerticalScrollBar().setUnitIncrement(15);
		checkersMainPanel.add(scrollPane_1);
		
		lobbyPanel = new JPanel();
		scrollPane_1.setViewportView(lobbyPanel);
		lobbyPanel.setBackground(new Color(46, 139, 87));
		lobbyPanel.setName("lobbyPanel");
		lobbyPanel.setPreferredSize(new Dimension(1193, 50000));
		lobbyPanel.setBounds(167, 62, 1193, 1000);
		
		lobbyPanel.setLayout(null);

		
		JPanel usernamesPanel = new JPanel();
		usernamesPanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		usernamesPanel.setBounds(0, 62, 167, 677);
		usernamesPanel.setName("Usernames Panel");
		checkersMainPanel.add(usernamesPanel);
		usernamesPanel.setLayout(null);
		
		JLabel usersLabel = new JLabel("Users");
		usersLabel.setBounds(59, 11, 46, 14);
		usersLabel.setHorizontalAlignment(SwingConstants.CENTER);
		usernamesPanel.add(usersLabel);
		
		currentUsersTextArea = new JTextArea();
		currentUsersTextArea.setEditable(false);
		currentUsersTextArea.setLineWrap(true);
		currentUsersTextArea.setBounds(0, 0, 4, 22);
		currentUsersTextArea.setName("CurrentUsersTextArea");
		
		
		JScrollPane usersScrollPane = new JScrollPane(currentUsersTextArea);
		usersScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
		usersScrollPane.setBounds(10, 36, 147, 630);
		usernamesPanel.add(usersScrollPane);
		

		
		JPanel lobbyChatPanel = new JPanel();
		lobbyChatPanel.setBackground(new Color(255, 255, 255));
		lobbyChatPanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		lobbyChatPanel.setBounds(167, 499, 1193, 210);
		lobbyChatPanel.setName("LobbyChatPanel");
		
		checkersMainPanel.add(lobbyChatPanel);
		
		lobbyChatTextArea = new JTextArea();
		lobbyChatTextArea.setEditable(false);
		lobbyChatTextArea.setLineWrap(true);
		lobbyChatTextArea.setColumns(107);
		lobbyChatTextArea.setWrapStyleWord(true);
		lobbyChatTextArea.setRows(16);
		lobbyChatTextArea.setName("LobbyChatTextArea");
		
		
		JScrollPane lobbyChatScrollPane = new JScrollPane(lobbyChatTextArea);
		lobbyChatPanel.add(lobbyChatScrollPane);
		
		
		JPanel messagePanel = new JPanel();
		messagePanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		messagePanel.setBounds(167, 709, 1193, 30);
		messagePanel.setName("MessagePanel");
		checkersMainPanel.add(messagePanel);
		
		messageTextField = new JTextField("username");
		messageTextField.setToolTipText("");
		messageTextField.setHorizontalAlignment(SwingConstants.LEFT);
		messageTextField.setColumns(107);
		messageTextField.setName("MessageTextField");
		
		messagePanel.add(messageTextField);
		
	}
	
	
	public JTextField getMessageTextField(){
		return messageTextField;
	}
	
	public JTextArea getCurrentUsers(){
		return currentUsersTextArea;
	}
	
	public JTextArea getLobbyChatTextArea(){
		return lobbyChatTextArea;
	}
	
	public JPanel getLobbyPanel(){
		return lobbyPanel;
	}
}
