package edu.wright.crowningkings.desktop;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.EventQueue;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JTextPane;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JScrollBar;
import java.awt.TextArea;
import java.awt.GridBagLayout;
import javax.swing.JLabel;
import javax.swing.JTabbedPane;
import java.awt.Color;
import javax.swing.border.EtchedBorder;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.GridLayout;
import javax.swing.SwingConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.LineBorder;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

public class CheckersLobbyUI extends JFrame {

	//private static final long serialVersionUID = 1L;
	
	//Not all of these are used might use them in the futre
	private JPanel checkersMainPanel;
	private JTextField messageTextField;
	private JTextArea currentUsersTextArea;
	private JTextArea lobbyChatTextArea;
	private JPanel currentLobbyPanel; //Might not need this later on


	/**
	 * Create the frame.
	 * Generated By WindowsBuilder Pro
	 * Variable names changed for Clarity
	 */
	public CheckersLobbyUI() {
		setResizable(false);
		setBackground(new Color(0, 0, 0));
		setTitle("Checkers Game");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1366, 768);
		checkersMainPanel = new JPanel();
		checkersMainPanel.setBackground(new Color(0, 0, 0));
		checkersMainPanel.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(checkersMainPanel);
		checkersMainPanel.setLayout(null);
		
		currentLobbyPanel = new JPanel();
		currentLobbyPanel.setBounds(167, 0, 1193, 434);
		currentLobbyPanel.setBackground(new Color(46, 139, 87));
		currentLobbyPanel.setName("CurrentLobbyPanel");
		checkersMainPanel.add(currentLobbyPanel);
		
		JPanel usernamesPanel = new JPanel();
		usernamesPanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		usernamesPanel.setBounds(0, 0, 167, 739);
		usernamesPanel.setName("Usernames Panel");
		checkersMainPanel.add(usernamesPanel);
		usernamesPanel.setLayout(null);
		
		JLabel usersLabel = new JLabel("Users");
		usersLabel.setHorizontalAlignment(SwingConstants.CENTER);
		usersLabel.setBounds(59, 11, 46, 14);
		usernamesPanel.add(usersLabel);
		
		currentUsersTextArea = new JTextArea();
		currentUsersTextArea.setEditable(false);
		currentUsersTextArea.setLineWrap(true);
		currentUsersTextArea.setBounds(0, 0, 4, 22);
		currentUsersTextArea.setName("CurrentUsersTextArea");
		
		JScrollPane usersScrollPane = new JScrollPane(currentUsersTextArea);
		usersScrollPane.setBounds(10, 36, 147, 692);
		usernamesPanel.add(usersScrollPane);
		

		//panel_1.add(textArea_1);
		
		JPanel lobbyChatPanel = new JPanel();
		lobbyChatPanel.setBackground(new Color(255, 255, 255));
		lobbyChatPanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		lobbyChatPanel.setBounds(167, 434, 1193, 275);
		lobbyChatPanel.setName("LobbyChatPanel");
		checkersMainPanel.add(lobbyChatPanel);
		
		lobbyChatTextArea = new JTextArea();
		lobbyChatTextArea.setEditable(false);
		lobbyChatTextArea.setLineWrap(true);
		lobbyChatTextArea.setColumns(107);
		lobbyChatTextArea.setWrapStyleWord(true);
		lobbyChatTextArea.setRows(16);
		lobbyChatTextArea.setName("LobbyChatTextArea");
		
		JScrollPane lobbyChatScrollPane = new JScrollPane(lobbyChatTextArea);
		lobbyChatPanel.add(lobbyChatScrollPane);
		
		
		JPanel messagePanel = new JPanel();
		messagePanel.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
		messagePanel.setBounds(167, 709, 1193, 30);
		messagePanel.setName("MessagePanel");
		checkersMainPanel.add(messagePanel);
		
		messageTextField = new JTextField();
		messageTextField.setToolTipText("");
		messageTextField.setHorizontalAlignment(SwingConstants.LEFT);
		messageTextField.setColumns(107);
		messageTextField.setName("MessageTextField");
		messagePanel.add(messageTextField);
	}
	
	//Get the text filed that a user inputs messages in
	public JTextField getMessageTextField(){
		return messageTextField;
	}
	
	//Get the text of the current users component
	public String getCurrentUsersTextAreaText(){
		return currentUsersTextArea.getText();
	}
	
	//Set the text of the current users component
	public void setCurrentUsersTextAreaText(String username){
		currentUsersTextArea.setText(username + "\n");
	}
	
	//Get all of the text from the lobby chat component
	public String getLobbyChatTextArea(){
		return lobbyChatTextArea.getText();
	}
	
	//Set the text of the lobby chat component
	public void setLobbyChatTextArea(String message){
		lobbyChatTextArea.setText(message);
	}
	
}
